directories:
  output: release
  buildResources: build
asar: false
asarUnpack:
  - '**/backend/**'
appId: com.app.juds
productName: Juds
files:
  - filter:
      - dist/my-app/**/*
      - electron/**/*
      - backend/**/*
win:
  target: nsis
  icon: src/assets/icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
electronVersion: 28.1.0
